2025-05-10 00:14:50,813 - root - INFO - Loaded cog: course_availability.py
2025-05-10 00:14:50,815 - root - INFO - Loaded cog: heat_outline.py
2025-05-10 00:14:50,816 - root - INFO - Loaded cog: course_info.py
2025-05-10 00:14:50,816 - discord.client - INFO - logging in using static token
2025-05-10 00:14:51,716 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 434f05320f023433ee4773a914ae5ec3).
2025-05-10 00:14:53,739 - root - INFO - Bot is logged in as UVIC Course Info Test (1370471918859190403)
2025-05-10 00:14:54,007 - root - INFO - Synced commands to guild ID: 1353592477671755906
2025-05-10 00:14:54,210 - discord.client - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/tom/projects/uvic-course-bot/venv/lib/python3.12/site-packages/discord/client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "/home/tom/projects/uvic-course-bot/main.py", line 59, in on_ready
    await bot.tree.sync(guild=discord.Object(id=guild_id))
  File "/home/tom/projects/uvic-course-bot/venv/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1131, in sync
    data = await self._http.bulk_upsert_guild_commands(self.client.application_id, guild.id, payload=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/projects/uvic-course-bot/venv/lib/python3.12/site-packages/discord/http.py", line 756, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2025-05-10 00:16:01,889 - root - INFO - Loaded cog: course_availability.py
2025-05-10 00:16:01,889 - root - INFO - Loaded cog: heat_outline.py
2025-05-10 00:16:01,889 - root - INFO - Loaded cog: course_info.py
2025-05-10 00:16:01,890 - discord.client - INFO - logging in using static token
2025-05-10 00:16:03,137 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 0508868226e19f527116667f4451c889).
2025-05-10 00:16:05,140 - root - INFO - Bot is logged in as UVIC Course Info Test (1370471918859190403)
2025-05-10 00:16:05,482 - root - INFO - Synced commands to guild ID: 1353592477671755906
2025-05-10 00:16:05,687 - discord.client - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/tom/projects/uvic-course-bot/venv/lib/python3.12/site-packages/discord/client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "/home/tom/projects/uvic-course-bot/main.py", line 59, in on_ready
    await bot.tree.sync(guild=discord.Object(id=guild_id))
  File "/home/tom/projects/uvic-course-bot/venv/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1131, in sync
    data = await self._http.bulk_upsert_guild_commands(self.client.application_id, guild.id, payload=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/projects/uvic-course-bot/venv/lib/python3.12/site-packages/discord/http.py", line 756, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
2025-05-10 00:17:15,444 - root - INFO - Loaded cog: course_availability.py
2025-05-10 00:17:15,445 - root - INFO - Loaded cog: heat_outline.py
2025-05-10 00:17:15,445 - root - INFO - Loaded cog: course_info.py
2025-05-10 00:17:15,445 - discord.client - INFO - logging in using static token
2025-05-10 00:17:16,262 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 738eb47070cfdc05321fff9ec4363681).
2025-05-10 00:17:18,275 - root - INFO - Bot is logged in as UVIC Course Info Test (1370471918859190403)
2025-05-10 00:17:18,425 - root - INFO - Synced commands to guild ID: 1353592477671755906
2025-05-10 00:21:49,042 - cogs.course_availability - INFO - Received availability command: ECE 471 01 2025
